
export const ERROR_CODES = {
    ERROR_GETTING_ARTICLES: "ERROR_GETTING_ARTICLES",
    ERROR_GETTING_ARTICLES_GIVEN_AUTHOR: "ERROR_GETTING_ARTICLES_GIVEN_AUTHOR",
    ERROR_GETTING_ARTICLE_BY_ID: "ERROR_GETTING_ARTICLE_BY_ID",
    ERROR_GETTING_LIST_OF_AUTHORS: "ERROR_GETTING_LIST_OF_AUTHORS",
}

export const KEYWORD_SEARCH = {
    PSYCHIATRY: "Psychiatry",
    THERAPY: "Therapy",
    DATA_SCIENCE: "Data Science",
    MACHINE_LEARNING: "Machine Learning"
}

export const TOP_TABS = {
    ARTICLE_PAGE: "Articles",
    AUTHOR_PAGE: "Authors"
}

