
export const ERROR_CODES = {
    ERROR_GETTING_ARTICLES: "ERROR_GETTING_ARTICLES",
    ERROR_GETTING_ARTICLES_GIVEN_AUTHOR: "ERROR_GETTING_ARTICLES_GIVEN_AUTHOR",
}

export const KEYWORD_SEARCH = {
    PSYCHIATRY: "Psychiatry",
    THERAPY: "Therapy",
    DATA_SCIENCE: "Data Science",
    MACHINE_LEARNING: "Machine Learning"
}

